
development:
  adapter: postgresql
  encoding: unicode
  database: busy_development
  pool: 5
  timeout: 5000
  username: busy
  password:

test:
 adapter: postgresql
  encoding: unicode
  database: busy_test
  pool: 5
  timeout: 5000
  username: busy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: busy_development
  pool: 5
  timeout: 5000
  username: busy_production
  password:
